// src/components/Header/Stack.tsx
import { techStack } from "@/utils/data";

export default function Stack() {
  return (
    <div className="w-full max-w-4xl">
      <h2 className="md:text-xl lg:text-2xl font-bold mb-3">
        I have experience with:
      </h2>
      <div className="flex flex-wrap gap-3 icon-float">
        {techStack.map((tech) => (
          <div
            key={tech.name}
            className={`flex items-center p-2 bg-gray-800 rounded-xl shadow-lg transition transform hover:scale-105 ${tech.hover}  hover:cursor-default text-sm`}
          >
            {<tech.icon className="w-5 h-5 lg:w-10 lg:h-10" stroke={1.25} />} 
            <span className="">{tech.name}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// src/components/sections/Stack.vue
<script setup lang="ts">
import { categorizedStack } from '@/utils/data'
</script>

<template>
  <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
    <div v-for="category in categorizedStack" :key="category.title" class="space-y-4">
      <h3
        class="text-[10px] font-bold uppercase tracking-widest text-slate-500 tech-font border-l-2 border-indigo-500 pl-2"
      >
        {{ category.title }}
      </h3>
      <div class="flex flex-wrap gap-2">
        <div
          v-for="tech in category.items"
          :key="tech.name"
          class="flex items-center gap-2 px-3 py-1.5 rounded-sm border border-white/5 bg-white/5 text-slate-300 transition-all duration-300 hover:border-indigo-500/50 hover:bg-indigo-500/10 hover:text-white"
        >
          <component :is="tech.icon" class="size-3.5" stroke-width="1.5" />
          <span class="text-[10px] tech-font font-medium">{{ tech.name }}</span>
        </div>
      </div>
    </div>
  </div>
</template>
