// src/components/sections/Stack.vue
<script setup lang="ts">
import { categorizedStack } from '@/utils/data'
</script>

<template>
  <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
    <div v-for="category in categorizedStack" :key="category.title" class="space-y-4">
      <h3
        class="text-[10px] font-bold uppercase tracking-widest text-slate-500 tech-font border-l-2 border-indigo-500 pl-2"
      >
        {{ category.title }}
      </h3>
      <div class="flex flex-wrap gap-2">
        <div
          v-for="tech in category.items"
          :key="tech.name"
          class="flex items-center gap-2 px-3 py-1.5 rounded-sm border border-white/5 bg-white/5 text-slate-300 transition-all duration-300 hover:border-indigo-500/50 hover:bg-indigo-500/10 hover:text-white"
        >
          <component :is="tech.icon" class="size-3.5" stroke-width="1.5" />
          <span class="text-[10px] tech-font font-medium">{{ tech.name }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

// src/components/sections/Stack.tsx
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { techStack } from "@/utils/data";
import { Button } from "../ui/button";

export default function Stack() {
  return (
    <Card className="flex-2 overflow-y-auto md:h-[80vh] lg:h-[60vh]">
      <CardHeader>
        <CardTitle>I have experience with:</CardTitle>
      </CardHeader>
      <CardContent className="flex flex-wrap gap-3">
        {techStack.map((tech) => (
          <Button
            variant="outline"
            key={tech.name}
            className={`flex transform items-center rounded-xl p-2 shadow-lg transition hover:scale-105 ${tech.color} md:text-lg lg:text-xl`}
          >
            {<tech.icon className="scale-150" stroke={1.25} />}
            <span>{tech.name}</span>
          </Button>
        ))}
      </CardContent>
    </Card>
  );
}
